repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check
          --force-exclude --fix
        language: python
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format
        language: python
        types_or: [python, pyi]
        require_serial: true
      - id: mypy
        name: mypy
        entry: mypy sqlglot tests
        language: system
        types: [ python ]
        files: ^(sqlglot/|tests/)
        pass_filenames: false
